### ISSUE TITLE
Lagging with datapacks

### ISSUE THREAD

**Issue by adoxentor** [shurf012/EnchantWithMob#2]
I have no idea how I caused it but here is the spark profile: [spark](https://spark.lucko.me/NpOsWtKJrG)
I had 2 second per tick.
modpack [https://www.curseforge.com/minecraft/modpacks/mineshafts-monsters](https://www.curseforge.com/minecraft/modpacks/mineshafts-monsters)
I applied the effect to a wandering trader and a friend applied it to me.

removing the mod fixed the lags, so did /kill @e

**Comment by shurf012** [comment]
I found that past versions caused out of memory and lag due to a bug that keeps increasing nbt tags due to my mistake. 
you should be try this new version
https://www.curseforge.com/minecraft/mc-mods/enchant-with-mob/files/3278813
